version: "3.7"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"

  divitrino:
    env_file:
      - .env
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    ports:
      - "3000:3000"
