version: "3.7"
services:
  postgres:
    env_file:
      - .env
    image: postgres
    ports:
      - "5432:5432"

  rest_api:
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
