version: "3.7"
services:
  postgres:
    env_file:
      - .env
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rest_api:
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
